//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionAbsenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int id_A { get; set; }
        public Nullable<System.DateTime> DateA { get; set; }
        public string type_Ab { get; set; }
        public Nullable<int> id_S { get; set; }
        public Nullable<int> id_P { get; set; }
        public string justf { get; set; }
    
        public virtual Prof Prof { get; set; }
        public virtual Stagiare Stagiare { get; set; }
    }
}
